# Generated by Django 6.0.4 on 2026-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='General', max_length=200),
            preserve_default=False,
        ),
    ]
